### ISSUE TITLE
Feature request : Version / Migration

### ISSUE THREAD

**Issue by ThibautMarechal** [adam-golab/redux-phoenix#4]
I'm having some issue on my application. 
Every time the structure of the reducers changes, or the initial state must be updated (ex: When a new version of the app is released), the users that has saved some of his store in a storage may have some issue between states version.

It could be nice to have a system that can handle the versioning between saved state.

My proposition is to save the version (incremented manually when the storage need to be updated)
If the version doesn't match:
- Another argument can handle the migration between versions
- If no migrations provided, we skip the rehydration.

For the moment i do it on my side but i think it could be nice to have that kind of feature in redux-phoenix.

What do you think ?

**Comment by adam-golab** [comment]
Hi @ThibautMarechal,
The idea sounds really cool. Do you know some reliable libraries that can be used for that? I'd like to avoid writing the whole functionality if migrations as it seems more like a topic for another library.

Also, I'm wondering if it won't be possible for you to implement and use custom `autoRehydrate` function for migrations. Of course, you should have information about state's version somewhere in the redux state and compare it somehow.
```js
const autoRehydrate = next => (reducer, initialState, enhancer) => {
  if (typeof initialState === 'function' && typeof enhancer === 'undefined') {
    enhancer = initialState;
    initialState = undefined;
  }
  function rehydrateReducer(state, action) {
    if (action.type === REHYDRATE) {
      const newState = action.payload.version !== state.version
        ? migrate(action.payload) // handle migrations
        : action.payload;
      
      return reducer(_.merge({}, state, newState), action);
    }
    return reducer(state, action);
  }
  return next(rehydrateReducer, initialState, enhancer);
};
```

Nevertheless, I'll try to implement it in a simple way in my free time.

**Comment by ThibautMarechal** [comment]
We do not a way to have the information in the "autoRehydrate" Enhancer. I Think the migration should happend here : 

```
export default function persistStore(store, {
  key = 'redux',
  whitelist = null,
  blacklist = null,
  storage = window.localStorage,
  expireDate = null,
  serialize = JSON.stringify,
  deserialize = JSON.parse,
  map = {},
  disabled = false,
  throttle = 0,
  migrations = {},
  version = 0,
} = {}) {
  return Promise.resolve(storage.getItem(key)).then(persistedJson => {
  const migratedJson = migrate(persitedJSon, migrations, version);
  [...]
}
```

The migrations may look like this : 

```
{
  0: {
    up: state => ...,
  },
  1: {
    down: state => ...,
    up: state => ...,
  },
  2: {
    down: state => ...,
  },
}
```

Handle migrations is pretty easy, i don't think the usage of an external package is needed except if we find the package matching the need.

**Comment by adam-golab** [comment]
@ThibautMarechal I opened a PR with the first draft of the migrations feature. Feel free to take a look and give some feedback, it will be really appreciated.

After updating CircleCI config to the version 2 I'll merge it to the next release.

**Comment by adam-golab** [comment]
Closing in favor of #5
